version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    hostname: "{{.Node.Hostname}}"
    environment:
      - node.name={{.Node.Hostname}}
      - cluster.name=bitel-logmanagement
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elastic-01,elastic-02,elastic-03
      - node.ml=false
      - xpack.ml.enabled=true
      - xpack.monitoring.enabled=true
      - xpack.security.enabled=false
      - xpack.watcher.enabled=true
      - bootstrap.memory_lock=false
      - TZ=America/Lima
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    deploy:
      mode: global
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 6G

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.0
    hostname: "{{.Node.Hostname}}"
    ports:
      - "8044:8044"
      - "514:514/udp"
    environment:
      - XPACK_MONITORING_ENABLED=true
      - TZ=America/Lima
    volumes:
      - logstash:/opt/logstash/config
      - /var/log/logstash:/var/log/logstash
    deploy:
      mode: global
      resources:
        limits:
          memory: 2G
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    hostname: "{{.Node.Hostname}}"
    environment:
      - xpack.monitoring.enabled=true
      - TZ=America/Lima
    volumes:
      - /opt/elk/kibana:/opt/kibana/config
    deploy:
      replicas: 1

  nginx:
    image: nginx
    hostname: "{{.Node.Hostname}}"
    ports:
      - "80:80"
      - "443:443"
    deploy:
      mode: global
    environment:
      - TZ=America/Lima
    volumes:
      - /opt/elk/nginx/conf:/etc/nginx
      - nginx_log:/var/log/nginx    

volumes:
  elasticsearch-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/elasticdata/elasticsearch-data'
  nginx_log:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/elk/nginx/logs'
  logstash:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/elk/logstash'
